// Generated by `anchor build`. Regenerate and re-copy from target/ if the program changes.
/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/compute_markets.json`.
 */
export type ComputeMarkets = {
  "address": "8xv1L7757szxo2XPrQL5AERPGZrJaYRKgqB9RgFkQCU2",
  "metadata": {
    "name": "computeMarkets",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Compute — on-chain prediction markets for trading on compute (FPMM)"
  },
  "instructions": [
    {
      "name": "acceptAdmin",
      "docs": [
        "Two-step admin transfer, step 2: the nominee accepts."
      ],
      "discriminator": [
        112,
        42,
        45,
        90,
        116,
        181,
        13,
        170
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "pendingAdmin",
          "signer": true
        }
      ],
      "args": []
    },
    {
      "name": "addLiquidity",
      "docs": [
        "Add liquidity to an already-seeded, OPEN market (Gnosis FPMM `addFunding`).",
        "",
        "The provider deposits `amount` collateral; the protocol mints a full set",
        "(`amount` YES + `amount` NO) into the pool and sends back the surplus of",
        "each side so the **price ratio is preserved**. Shares are minted pro-rata",
        "to `amount / max(reserve_yes, reserve_no)`.",
        "",
        "Rounding (favors the pool / existing LPs):",
        "* `shares_minted` is FLOORED — the entrant is never over-credited.",
        "* the reserve the pool keeps of each side is CEILED — the send-back to the",
        "LP is the smaller value, so the pool retains at least its fair share.",
        "A dust add that would mint 0 shares is rejected (`ZeroAmount`)."
      ],
      "discriminator": [
        181,
        157,
        89,
        67,
        143,
        182,
        52,
        72
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "yesMint",
          "writable": true
        },
        {
          "name": "noMint",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "poolYes",
          "writable": true
        },
        {
          "name": "poolNo",
          "writable": true
        },
        {
          "name": "lpCollateral",
          "writable": true
        },
        {
          "name": "lpYes",
          "writable": true
        },
        {
          "name": "lpNo",
          "writable": true
        },
        {
          "name": "position",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "market"
              },
              {
                "kind": "account",
                "path": "lp"
              }
            ]
          }
        },
        {
          "name": "lp",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "assertOutcome",
      "docs": [
        "Optimistic resolution, step 1 (PERMISSIONLESS): anyone asserts a binary",
        "outcome by posting `config.bond_amount` collateral into the SEPARATE bond",
        "vault. Opens the dispute window; the assertion either finalizes undisputed",
        "(`finalize_assertion`, asserter reclaims the bond) or is disputed",
        "(`dispute_assertion`) and settled by the guardian (`resolve_dispute`)."
      ],
      "discriminator": [
        44,
        170,
        123,
        232,
        110,
        150,
        247,
        36
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "collateralMint"
        },
        {
          "name": "bondVault",
          "docs": [
            "The bond escrow, created on first assert. SEPARATE from `market.vault`, so",
            "bonds never touch the collateral-conservation invariant."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  110,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "asserterCollateral",
          "writable": true
        },
        {
          "name": "asserter",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "rent",
          "address": "SysvarRent111111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "outcome",
          "type": "u8"
        }
      ]
    },
    {
      "name": "buy",
      "docs": [
        "Buy `outcome` by investing `collateral_in`. Reverts if fewer than",
        "`min_tokens_out` would be received, if paused, or after `close_time`."
      ],
      "discriminator": [
        102,
        6,
        61,
        18,
        1,
        218,
        235,
        234
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "yesMint",
          "writable": true
        },
        {
          "name": "noMint",
          "writable": true
        },
        {
          "name": "poolYes",
          "writable": true
        },
        {
          "name": "poolNo",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "userOutcome",
          "writable": true
        },
        {
          "name": "userCollateral",
          "writable": true
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "outcome",
          "type": "u8"
        },
        {
          "name": "collateralIn",
          "type": "u64"
        },
        {
          "name": "minTokensOut",
          "type": "u64"
        }
      ]
    },
    {
      "name": "claimPool",
      "docs": [
        "After settlement, a liquidity provider reclaims their **pro-rata slice** of",
        "the pool's outcome tokens as collateral. Claims the caller's ENTIRE",
        "position: with `shares = position.shares` and `S = total_shares`, the",
        "provider's slice of each reserve is `c_i = floor(reserve_i * shares / S)`",
        "(FLOORED so leftover dust stays with un-claimed providers / the vault).",
        "Payout per settlement state:",
        "* binary RESOLVED → the winning side's slice (`cy` if YES won, else `cn`);",
        "* scalar RESOLVED → `scalar_payout(cy, f, LONG) + scalar_payout(cn, f, SHORT)`;",
        "* VOID → `cy/2 + cn/2`.",
        "Burns `cy`/`cn` from the pools, transfers `payout` collateral out, and",
        "zeroes the caller's shares (and decrements `total_shares`)."
      ],
      "discriminator": [
        70,
        215,
        67,
        50,
        142,
        244,
        218,
        130
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "yesMint",
          "writable": true
        },
        {
          "name": "noMint",
          "writable": true
        },
        {
          "name": "poolYes",
          "writable": true
        },
        {
          "name": "poolNo",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "lpCollateral",
          "writable": true
        },
        {
          "name": "position",
          "docs": [
            "The caller's own position (seeds bind it to `market` + `lp`), so each LP",
            "claims exactly their pro-rata slice."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "market"
              },
              {
                "kind": "account",
                "path": "lp"
              }
            ]
          }
        },
        {
          "name": "lp",
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "collectFees",
      "docs": [
        "Admin withdraws accrued protocol fees for this market."
      ],
      "discriminator": [
        164,
        152,
        207,
        99,
        30,
        186,
        19,
        182
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "adminCollateral",
          "writable": true
        },
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "createMarket",
      "docs": [
        "Create a new binary market. Permissionless: anyone may create one and",
        "nominate a `resolver`. Trading halts at `close_time`; the outcome may be",
        "proposed at/after `resolution_time` (`close_time <= resolution_time`)."
      ],
      "discriminator": [
        103,
        226,
        97,
        235,
        200,
        188,
        251,
        254
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "config.market_count",
                "account": "config"
              }
            ]
          }
        },
        {
          "name": "yesMint",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  121,
                  101,
                  115
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "noMint",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  110,
                  111
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "collateralMint"
        },
        {
          "name": "creator",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "rent",
          "address": "SysvarRent111111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "question",
          "type": "string"
        },
        {
          "name": "resolutionSource",
          "type": "string"
        },
        {
          "name": "closeTime",
          "type": "i64"
        },
        {
          "name": "resolutionTime",
          "type": "i64"
        },
        {
          "name": "resolver",
          "type": "pubkey"
        },
        {
          "name": "resolverKind",
          "type": "u8"
        },
        {
          "name": "oracleFeed",
          "type": "pubkey"
        },
        {
          "name": "oracleStrike",
          "type": "i64"
        },
        {
          "name": "oracleComparison",
          "type": "u8"
        },
        {
          "name": "oracleMaxStaleness",
          "type": "i64"
        },
        {
          "name": "marketKind",
          "type": "u8"
        },
        {
          "name": "lowerBound",
          "type": "i64"
        },
        {
          "name": "upperBound",
          "type": "i64"
        }
      ]
    },
    {
      "name": "disputeAssertion",
      "docs": [
        "Optimistic resolution, step 2a (PERMISSIONLESS): challenge an open assertion",
        "by posting an equal bond into the bond vault, within the dispute window. A",
        "disputed assertion can no longer finalize on its own — only the guardian's",
        "`resolve_dispute` settles it (awarding both bonds to the correct asserter)."
      ],
      "discriminator": [
        27,
        132,
        244,
        216,
        101,
        77,
        138,
        55
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "bondVault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  110,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "disputerCollateral",
          "writable": true
        },
        {
          "name": "disputer",
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "disputeVoid",
      "docs": [
        "Guardian veto: during the dispute window, void a proposed outcome (→ 50/50",
        "refund). Use when a proposal is wrong or the resolver is compromised."
      ],
      "discriminator": [
        89,
        108,
        102,
        82,
        100,
        33,
        200,
        14
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "guardian",
          "signer": true
        }
      ],
      "args": []
    },
    {
      "name": "finalizeAssertion",
      "docs": [
        "Optimistic resolution, step 2b (PERMISSIONLESS): finalize an UNDISPUTED",
        "assertion once the dispute window has elapsed. Refunds the asserter's bond",
        "from the bond vault (PDA-signed) and resolves the market to the asserted",
        "outcome. Disputed assertions must go through `resolve_dispute` instead."
      ],
      "discriminator": [
        104,
        239,
        27,
        154,
        183,
        226,
        14,
        1
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "bondVault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  110,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "asserterCollateral",
          "writable": true
        },
        {
          "name": "asserter",
          "docs": [
            "The original asserter (must match `market.asserter`); reclaims the bond."
          ],
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "finalizeOutcome",
      "docs": [
        "Step 2 of resolution: finalize a proposed outcome once the dispute window",
        "has elapsed. Permissionless — anyone may crank it."
      ],
      "discriminator": [
        122,
        242,
        226,
        81,
        187,
        211,
        79,
        179
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "cranker",
          "signer": true
        }
      ],
      "args": []
    },
    {
      "name": "initPriceFeed",
      "docs": [
        "Initialize an on-chain price feed. The `feed` account is created fresh",
        "(pass a new keypair). In production its `authority` is a Switchboard",
        "On-Demand Function's enclave key or a committee multisig — whichever bridges",
        "the licensed off-chain index on-chain."
      ],
      "discriminator": [
        27,
        209,
        184,
        5,
        152,
        116,
        136,
        16
      ],
      "accounts": [
        {
          "name": "feed",
          "writable": true,
          "signer": true
        },
        {
          "name": "authority",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "description",
          "type": "string"
        },
        {
          "name": "decimals",
          "type": "u8"
        }
      ]
    },
    {
      "name": "initialize",
      "docs": [
        "Initialize the global config (one per deployment).",
        "",
        "* `fee_bps` — taker fee on buy/sell (e.g. 100 = 1%), capped at `MAX_FEE_BPS`.",
        "* `lp_fee_bps` — fraction OF THE TAKER FEE routed to LPs, in basis points",
        "(0..=10_000; 10_000 = the entire fee to LPs).",
        "* `dispute_period` — seconds between a proposed outcome and payout unlock.",
        "* `guardian` — key allowed to pause and to veto a proposed outcome.",
        "* `bond_amount` — the bond required to `assert_outcome` / `dispute_assertion`",
        "on an optimistic-resolver market (0 disables optimistic assertions)."
      ],
      "discriminator": [
        175,
        175,
        109,
        31,
        13,
        152,
        155,
        237
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "collateralMint"
        },
        {
          "name": "admin",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "feeBps",
          "type": "u16"
        },
        {
          "name": "lpFeeBps",
          "type": "u16"
        },
        {
          "name": "disputePeriod",
          "type": "i64"
        },
        {
          "name": "guardian",
          "type": "pubkey"
        },
        {
          "name": "bondAmount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "proposeFromOracle",
      "docs": [
        "Oracle resolution (step 1, permissionless): derive the proposed outcome",
        "for a `RESOLVER_ORACLE_FEED` market by comparing the bound price feed's",
        "value to the market's strike. Enters the same dispute window as a manual",
        "proposal, so the guardian can still veto a manipulated feed."
      ],
      "discriminator": [
        244,
        4,
        149,
        46,
        51,
        227,
        30,
        189
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "feed"
        },
        {
          "name": "cranker",
          "signer": true
        }
      ],
      "args": []
    },
    {
      "name": "proposeOutcome",
      "docs": [
        "Step 1 of resolution: the market's `resolver` proposes a winning outcome",
        "at/after `resolution_time`. Opens the dispute window; payouts stay locked."
      ],
      "discriminator": [
        147,
        78,
        55,
        89,
        179,
        236,
        26,
        248
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "resolver",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "outcome",
          "type": "u8"
        }
      ]
    },
    {
      "name": "proposeScalar",
      "docs": [
        "Step 1 of resolution for a SCALAR market: the market's `resolver` proposes",
        "a settlement `value` at/after `resolution_time`. Mirrors `propose_outcome`",
        "but records a raw scalar value (mapped to a fraction at finalize) instead",
        "of a YES/NO outcome. Opens the same dispute window; payouts stay locked."
      ],
      "discriminator": [
        212,
        107,
        139,
        60,
        135,
        242,
        216,
        0
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "resolver",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "value",
          "type": "i64"
        }
      ]
    },
    {
      "name": "publishPrice",
      "docs": [
        "Post a new value to a price feed (feed authority only). `value` is in the",
        "feed's native fixed-point integer scale (see `decimals`)."
      ],
      "discriminator": [
        117,
        13,
        6,
        171,
        29,
        204,
        11,
        1
      ],
      "accounts": [
        {
          "name": "feed",
          "writable": true
        },
        {
          "name": "authority",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "value",
          "type": "i64"
        }
      ]
    },
    {
      "name": "redeem",
      "docs": [
        "Redeem `amount` of the winning outcome token for `amount` collateral."
      ],
      "discriminator": [
        184,
        12,
        86,
        149,
        70,
        196,
        97,
        225
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "winningMint",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "userOutcome",
          "writable": true
        },
        {
          "name": "userCollateral",
          "writable": true
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "redeemScalar",
      "docs": [
        "Redeem `amount` of a SCALAR market's LONG (yes_mint) or SHORT (no_mint)",
        "token for its settled value. `is_long` is inferred from which of the two",
        "mints the user's outcome ATA holds; the payout is",
        "`scalar_payout(amount, settlement_fraction, is_long)` (floor-rounded so the",
        "vault is never overpaid)."
      ],
      "discriminator": [
        33,
        153,
        69,
        243,
        222,
        230,
        110,
        41
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "winningMint",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "userOutcome",
          "writable": true
        },
        {
          "name": "userCollateral",
          "writable": true
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "redeemVoid",
      "docs": [
        "Redeem `amount` of EITHER outcome token on a voided market for half of",
        "collateral per token (rounded down). 50/50 refund that conserves the vault."
      ],
      "discriminator": [
        43,
        230,
        73,
        156,
        254,
        174,
        252,
        196
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "winningMint",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "userOutcome",
          "writable": true
        },
        {
          "name": "userCollateral",
          "writable": true
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "removeLiquidity",
      "docs": [
        "Remove liquidity from an OPEN market (Gnosis FPMM `removeFunding`).",
        "",
        "Burns `shares` of the caller's pool position and transfers their pro-rata",
        "slice of each reserve out to the LP's outcome ATAs:",
        "`send_i = floor(reserve_i * shares / total_shares)` (FLOORED so remaining",
        "LPs are never short-changed). Collateral is unchanged — the outcome tokens",
        "stay outstanding, just held by the LP, who can later merge equal YES+NO via",
        "`sell` / redemption or hold to settlement."
      ],
      "discriminator": [
        80,
        85,
        209,
        72,
        24,
        206,
        177,
        108
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          },
          "relations": [
            "position"
          ]
        },
        {
          "name": "poolYes",
          "writable": true
        },
        {
          "name": "poolNo",
          "writable": true
        },
        {
          "name": "lpYes",
          "writable": true
        },
        {
          "name": "lpNo",
          "writable": true
        },
        {
          "name": "position",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "market"
              },
              {
                "kind": "account",
                "path": "lp"
              }
            ]
          }
        },
        {
          "name": "owner",
          "relations": [
            "position"
          ]
        },
        {
          "name": "lp",
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "resolveDispute",
      "docs": [
        "Optimistic resolution, step 2c (GUARDIAN only): settle a DISPUTED assertion.",
        "The guardian (the DVM / council stand-in) declares the `correct_outcome`;",
        "the whole `2 * bond` escrow goes to whoever asserted it (the asserter if",
        "`proposed_outcome == correct_outcome`, else the disputer), PDA-signed out of",
        "the bond vault. The market resolves to `correct_outcome`."
      ],
      "discriminator": [
        231,
        6,
        202,
        6,
        96,
        103,
        12,
        230
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "bondVault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  110,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "winnerCollateral",
          "docs": [
            "The winner's collateral ATA — its owner/mint are checked in the handler",
            "against the guardian's ruling (asserter or disputer)."
          ],
          "writable": true
        },
        {
          "name": "guardian",
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "correctOutcome",
          "type": "u8"
        }
      ]
    },
    {
      "name": "seedLiquidity",
      "docs": [
        "Seed the AMM with initial liquidity at 50/50 odds. Callable once, by the",
        "market creator, before any trading."
      ],
      "discriminator": [
        180,
        57,
        94,
        35,
        73,
        48,
        13,
        11
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "yesMint",
          "writable": true
        },
        {
          "name": "noMint",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "poolYes",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  111,
                  111,
                  108,
                  95,
                  121,
                  101,
                  115
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "poolNo",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  111,
                  111,
                  108,
                  95,
                  110,
                  111
                ]
              },
              {
                "kind": "account",
                "path": "market"
              }
            ]
          }
        },
        {
          "name": "lpCollateral",
          "writable": true
        },
        {
          "name": "position",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "market"
              },
              {
                "kind": "account",
                "path": "lp"
              }
            ]
          }
        },
        {
          "name": "lp",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "rent",
          "address": "SysvarRent111111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "sell",
      "docs": [
        "Sell `outcome` to withdraw `collateral_out` (gross). Reverts if more than",
        "`max_tokens_in` would be required, if paused, or after `close_time`."
      ],
      "discriminator": [
        51,
        230,
        133,
        164,
        1,
        127,
        131,
        173
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "yesMint",
          "writable": true
        },
        {
          "name": "noMint",
          "writable": true
        },
        {
          "name": "poolYes",
          "writable": true
        },
        {
          "name": "poolNo",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "userOutcome",
          "writable": true
        },
        {
          "name": "userCollateral",
          "writable": true
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "outcome",
          "type": "u8"
        },
        {
          "name": "collateralOut",
          "type": "u64"
        },
        {
          "name": "maxTokensIn",
          "type": "u64"
        }
      ]
    },
    {
      "name": "setAdmin",
      "docs": [
        "Two-step admin transfer, step 1: nominate a new admin."
      ],
      "discriminator": [
        251,
        163,
        0,
        52,
        91,
        194,
        187,
        92
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "newAdmin",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "setBondAmount",
      "docs": [
        "Update the optimistic-resolver bond (admin only). No bound beyond type; 0",
        "disables `assert_outcome`."
      ],
      "discriminator": [
        190,
        139,
        80,
        7,
        10,
        199,
        21,
        2
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "value",
          "type": "u64"
        }
      ]
    },
    {
      "name": "setFeeBps",
      "docs": [
        "Update the taker fee (admin only), re-checked against `MAX_FEE_BPS`."
      ],
      "discriminator": [
        2,
        161,
        245,
        141,
        111,
        32,
        39,
        198
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "feeBps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "setGuardian",
      "docs": [
        "Update the guardian (admin only)."
      ],
      "discriminator": [
        147,
        243,
        50,
        121,
        154,
        164,
        50,
        30
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "guardian",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "setLpFeeBps",
      "docs": [
        "Update the LP fee share (admin only), re-validated `<= 10_000` bps."
      ],
      "discriminator": [
        255,
        79,
        85,
        199,
        175,
        171,
        86,
        4
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "value",
          "type": "u16"
        }
      ]
    },
    {
      "name": "setPaused",
      "docs": [
        "Pause or unpause all trading. Callable by the admin or the guardian."
      ],
      "discriminator": [
        91,
        60,
        125,
        192,
        176,
        225,
        166,
        218
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "authority",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "voidStale",
      "docs": [
        "Liveness escape hatch: if the resolver never proposes, anyone may void a",
        "stale market `VOID_GRACE_PERIOD` after `resolution_time`, freeing collateral."
      ],
      "discriminator": [
        203,
        244,
        15,
        146,
        222,
        43,
        30,
        226
      ],
      "accounts": [
        {
          "name": "market",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "market.market_id",
                "account": "market"
              }
            ]
          }
        },
        {
          "name": "cranker",
          "signer": true
        }
      ],
      "args": []
    }
  ],
  "accounts": [
    {
      "name": "config",
      "discriminator": [
        155,
        12,
        170,
        224,
        30,
        250,
        204,
        130
      ]
    },
    {
      "name": "liquidityPosition",
      "discriminator": [
        153,
        56,
        106,
        34,
        55,
        42,
        113,
        176
      ]
    },
    {
      "name": "market",
      "discriminator": [
        219,
        190,
        213,
        55,
        0,
        227,
        198,
        154
      ]
    },
    {
      "name": "priceFeed",
      "discriminator": [
        189,
        103,
        252,
        23,
        152,
        35,
        243,
        156
      ]
    }
  ],
  "events": [
    {
      "name": "assertionDisputed",
      "discriminator": [
        171,
        153,
        23,
        45,
        153,
        155,
        200,
        250
      ]
    },
    {
      "name": "disputeResolved",
      "discriminator": [
        121,
        64,
        249,
        153,
        139,
        128,
        236,
        187
      ]
    },
    {
      "name": "feesCollected",
      "discriminator": [
        233,
        23,
        117,
        225,
        107,
        178,
        254,
        8
      ]
    },
    {
      "name": "liquidityAdded",
      "discriminator": [
        154,
        26,
        221,
        108,
        238,
        64,
        217,
        161
      ]
    },
    {
      "name": "liquidityRemoved",
      "discriminator": [
        225,
        105,
        216,
        39,
        124,
        116,
        169,
        189
      ]
    },
    {
      "name": "liquiditySeeded",
      "discriminator": [
        147,
        232,
        14,
        56,
        38,
        188,
        80,
        31
      ]
    },
    {
      "name": "marketCreated",
      "discriminator": [
        88,
        184,
        130,
        231,
        226,
        84,
        6,
        58
      ]
    },
    {
      "name": "marketResolved",
      "discriminator": [
        89,
        67,
        230,
        95,
        143,
        106,
        199,
        202
      ]
    },
    {
      "name": "marketVoided",
      "discriminator": [
        217,
        12,
        138,
        39,
        108,
        75,
        89,
        26
      ]
    },
    {
      "name": "outcomeAsserted",
      "discriminator": [
        115,
        44,
        90,
        18,
        8,
        191,
        8,
        107
      ]
    },
    {
      "name": "outcomeProposed",
      "discriminator": [
        100,
        79,
        89,
        60,
        234,
        81,
        68,
        43
      ]
    },
    {
      "name": "pausedSet",
      "discriminator": [
        171,
        125,
        127,
        156,
        233,
        81,
        68,
        66
      ]
    },
    {
      "name": "poolClaimed",
      "discriminator": [
        36,
        11,
        190,
        83,
        128,
        77,
        196,
        150
      ]
    },
    {
      "name": "priceFeedInitialized",
      "discriminator": [
        215,
        208,
        148,
        233,
        198,
        216,
        185,
        183
      ]
    },
    {
      "name": "pricePublished",
      "discriminator": [
        161,
        182,
        51,
        133,
        25,
        192,
        179,
        140
      ]
    },
    {
      "name": "redeemed",
      "discriminator": [
        14,
        29,
        183,
        71,
        31,
        165,
        107,
        38
      ]
    },
    {
      "name": "scalarProposed",
      "discriminator": [
        33,
        173,
        142,
        204,
        39,
        191,
        148,
        142
      ]
    },
    {
      "name": "tradeExecuted",
      "discriminator": [
        41,
        110,
        64,
        129,
        60,
        79,
        179,
        80
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "feeTooHigh",
      "msg": "Fee exceeds the maximum (1000 bps)"
    },
    {
      "code": 6001,
      "name": "invalidParameter",
      "msg": "Invalid parameter"
    },
    {
      "code": 6002,
      "name": "invalidTimeWindow",
      "msg": "Invalid time window (need 0 < now < close_time <= resolution_time <= horizon)"
    },
    {
      "code": 6003,
      "name": "stringTooLong",
      "msg": "String exceeds maximum length"
    },
    {
      "code": 6004,
      "name": "unsupportedResolverKind",
      "msg": "Unsupported resolver kind"
    },
    {
      "code": 6005,
      "name": "marketNotOpen",
      "msg": "Market is not open for trading"
    },
    {
      "code": 6006,
      "name": "marketClosed",
      "msg": "Market is closed for trading"
    },
    {
      "code": 6007,
      "name": "paused",
      "msg": "Protocol is paused"
    },
    {
      "code": 6008,
      "name": "alreadySeeded",
      "msg": "Market has already been seeded with liquidity"
    },
    {
      "code": 6009,
      "name": "noLiquidity",
      "msg": "Market has no liquidity"
    },
    {
      "code": 6010,
      "name": "zeroAmount",
      "msg": "Amount must be greater than zero"
    },
    {
      "code": 6011,
      "name": "insufficientShares",
      "msg": "Insufficient pool shares for this operation"
    },
    {
      "code": 6012,
      "name": "invalidOutcome",
      "msg": "Invalid outcome (must be 0=YES or 1=NO)"
    },
    {
      "code": 6013,
      "name": "unauthorized",
      "msg": "unauthorized"
    },
    {
      "code": 6014,
      "name": "wrongMint",
      "msg": "Wrong token mint for this account"
    },
    {
      "code": 6015,
      "name": "wrongOwner",
      "msg": "Wrong owner for this token account"
    },
    {
      "code": 6016,
      "name": "slippageExceeded",
      "msg": "Slippage tolerance exceeded"
    },
    {
      "code": 6017,
      "name": "insufficientLiquidity",
      "msg": "Insufficient liquidity for this trade"
    },
    {
      "code": 6018,
      "name": "notResolved",
      "msg": "Market has not been resolved yet"
    },
    {
      "code": 6019,
      "name": "notProposed",
      "msg": "No outcome has been proposed"
    },
    {
      "code": 6020,
      "name": "notVoid",
      "msg": "Market is not voided"
    },
    {
      "code": 6021,
      "name": "disputeWindowOpen",
      "msg": "Dispute window is still open"
    },
    {
      "code": 6022,
      "name": "disputeWindowClosed",
      "msg": "Dispute window has closed"
    },
    {
      "code": 6023,
      "name": "tooEarlyToResolve",
      "msg": "Too early to resolve this market"
    },
    {
      "code": 6024,
      "name": "tooEarlyToVoid",
      "msg": "Too early to void this market"
    },
    {
      "code": 6025,
      "name": "nothingToClaim",
      "msg": "Nothing to claim"
    },
    {
      "code": 6026,
      "name": "wrongResolverKind",
      "msg": "Wrong resolver kind for this instruction"
    },
    {
      "code": 6027,
      "name": "wrongMarketKind",
      "msg": "Wrong market kind for this instruction"
    },
    {
      "code": 6028,
      "name": "unsupportedMarketKind",
      "msg": "Unsupported market kind"
    },
    {
      "code": 6029,
      "name": "invalidScalarRange",
      "msg": "Invalid scalar range (need lower_bound < upper_bound)"
    },
    {
      "code": 6030,
      "name": "invalidComparison",
      "msg": "Invalid oracle comparison code"
    },
    {
      "code": 6031,
      "name": "feedHasNoValue",
      "msg": "Price feed has no published value yet"
    },
    {
      "code": 6032,
      "name": "staleFeed",
      "msg": "Price feed value is too stale to resolve"
    },
    {
      "code": 6033,
      "name": "noBondConfigured",
      "msg": "No bond is configured for optimistic assertions"
    },
    {
      "code": 6034,
      "name": "alreadyDisputed",
      "msg": "Assertion has already been disputed"
    },
    {
      "code": 6035,
      "name": "selfDispute",
      "msg": "Cannot dispute your own assertion"
    },
    {
      "code": 6036,
      "name": "disputeUnresolved",
      "msg": "Disputed assertion must be settled by the guardian"
    },
    {
      "code": 6037,
      "name": "mathOverflow",
      "msg": "Arithmetic overflow"
    }
  ],
  "types": [
    {
      "name": "assertionDisputed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "disputer",
            "type": "pubkey"
          }
        ]
      }
    },
    {
      "name": "config",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "type": "pubkey"
          },
          {
            "name": "pendingAdmin",
            "type": "pubkey"
          },
          {
            "name": "guardian",
            "type": "pubkey"
          },
          {
            "name": "collateralMint",
            "type": "pubkey"
          },
          {
            "name": "feeBps",
            "type": "u16"
          },
          {
            "name": "lpFeeBps",
            "docs": [
              "Fraction OF THE TAKER FEE routed to LPs, in basis points (0..=10_000).",
              "The remainder of each fee accrues to the protocol (`fee_accrued`)."
            ],
            "type": "u16"
          },
          {
            "name": "disputePeriod",
            "type": "i64"
          },
          {
            "name": "marketCount",
            "type": "u64"
          },
          {
            "name": "paused",
            "type": "bool"
          },
          {
            "name": "bondAmount",
            "docs": [
              "Bond required to `assert_outcome` / `dispute_assertion` on an optimistic",
              "market (0 disables optimistic assertions). Settable via `set_bond_amount`."
            ],
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "disputeResolved",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "outcome",
            "type": "u8"
          },
          {
            "name": "winner",
            "type": "pubkey"
          }
        ]
      }
    },
    {
      "name": "feesCollected",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "liquidityAdded",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "provider",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "sharesMinted",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "liquidityPosition",
      "docs": [
        "One liquidity provider's pool position in one market. PDA seeds",
        "`[LP_SEED, market, owner]`. `shares / market.total_shares` is the provider's",
        "fraction of the AMM reserves; created on `seed_liquidity` (the creator) or the",
        "provider's first `add_liquidity`, and drained to 0 by `claim_pool`."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "shares",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "liquidityRemoved",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "provider",
            "type": "pubkey"
          },
          {
            "name": "shares",
            "type": "u64"
          },
          {
            "name": "yesOut",
            "type": "u64"
          },
          {
            "name": "noOut",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "liquiditySeeded",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "market",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "marketId",
            "type": "u64"
          },
          {
            "name": "creator",
            "type": "pubkey"
          },
          {
            "name": "resolver",
            "type": "pubkey"
          },
          {
            "name": "resolverKind",
            "type": "u8"
          },
          {
            "name": "marketKind",
            "docs": [
              "`MARKET_BINARY` or `MARKET_SCALAR`. Scalar markets reuse the binary FPMM",
              "(YES=LONG, NO=SHORT) and differ only in resolution + redemption."
            ],
            "type": "u8"
          },
          {
            "name": "lowerBound",
            "docs": [
              "Scalar range `[lower_bound, upper_bound]` (used when `market_kind ==",
              "MARKET_SCALAR`; both 0 for binary). Settlement clamps the resolved value",
              "to this range and maps it to a fraction in `[0, PRICE_SCALE]`."
            ],
            "type": "i64"
          },
          {
            "name": "upperBound",
            "type": "i64"
          },
          {
            "name": "proposedValue",
            "docs": [
              "Proposed scalar settlement value (parallels `proposed_outcome`). Set by",
              "`propose_scalar` / `propose_from_oracle` for scalar markets."
            ],
            "type": "i64"
          },
          {
            "name": "settlementFraction",
            "docs": [
              "Resolved settlement fraction `f` scaled to `PRICE_SCALE`, in",
              "`[0, PRICE_SCALE]`. Set at `finalize_outcome` for scalar markets."
            ],
            "type": "u32"
          },
          {
            "name": "oracleFeed",
            "docs": [
              "Oracle config (used when `resolver_kind == RESOLVER_ORACLE_FEED`)."
            ],
            "type": "pubkey"
          },
          {
            "name": "oracleStrike",
            "type": "i64"
          },
          {
            "name": "oracleComparison",
            "type": "u8"
          },
          {
            "name": "oracleMaxStaleness",
            "type": "i64"
          },
          {
            "name": "collateralMint",
            "type": "pubkey"
          },
          {
            "name": "yesMint",
            "type": "pubkey"
          },
          {
            "name": "noMint",
            "type": "pubkey"
          },
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "poolYes",
            "type": "pubkey"
          },
          {
            "name": "poolNo",
            "type": "pubkey"
          },
          {
            "name": "reserveYes",
            "type": "u64"
          },
          {
            "name": "reserveNo",
            "type": "u64"
          },
          {
            "name": "lp",
            "docs": [
              "The initial liquidity provider (informational; the creator who seeded).",
              "Per-provider balances live in [`LiquidityPosition`] PDAs."
            ],
            "type": "pubkey"
          },
          {
            "name": "totalShares",
            "docs": [
              "Total pool shares outstanding across all providers. A provider owns",
              "`position.shares / total_shares` of the AMM reserves."
            ],
            "type": "u64"
          },
          {
            "name": "collateral",
            "docs": [
              "Collateral backing outstanding tokens (excludes accrued fees)."
            ],
            "type": "u64"
          },
          {
            "name": "feeAccrued",
            "type": "u64"
          },
          {
            "name": "state",
            "type": "u8"
          },
          {
            "name": "outcome",
            "type": "u8"
          },
          {
            "name": "proposedOutcome",
            "type": "u8"
          },
          {
            "name": "asserter",
            "docs": [
              "Optimistic resolver (`RESOLVER_OPTIMISTIC`) bookkeeping. `asserter` posted",
              "the open assertion's bond; `disputer` (if any) posted the matching bond;",
              "`bond` is the per-side bond escrowed in the bond vault (0 once settled);",
              "`disputed` flags that the assertion is contested (→ `resolve_dispute`)."
            ],
            "type": "pubkey"
          },
          {
            "name": "disputer",
            "type": "pubkey"
          },
          {
            "name": "bond",
            "type": "u64"
          },
          {
            "name": "disputed",
            "type": "bool"
          },
          {
            "name": "closeTime",
            "type": "i64"
          },
          {
            "name": "resolutionTime",
            "type": "i64"
          },
          {
            "name": "resolvedAt",
            "type": "i64"
          },
          {
            "name": "question",
            "type": "string"
          },
          {
            "name": "resolutionSource",
            "type": "string"
          },
          {
            "name": "reserved",
            "docs": [
              "Forward-compat padding for future oracle resolver configs."
            ],
            "type": {
              "array": [
                "u8",
                64
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "marketCreated",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "marketId",
            "type": "u64"
          },
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "creator",
            "type": "pubkey"
          },
          {
            "name": "resolver",
            "type": "pubkey"
          },
          {
            "name": "closeTime",
            "type": "i64"
          },
          {
            "name": "resolutionTime",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "marketResolved",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "outcome",
            "type": "u8"
          },
          {
            "name": "settlementFraction",
            "docs": [
              "Scalar settlement fraction (0 for binary markets)."
            ],
            "type": "u32"
          },
          {
            "name": "resolvedAt",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "marketVoided",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "reason",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "outcomeAsserted",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "asserter",
            "type": "pubkey"
          },
          {
            "name": "outcome",
            "type": "u8"
          },
          {
            "name": "bond",
            "type": "u64"
          },
          {
            "name": "assertedAt",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "outcomeProposed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "resolver",
            "type": "pubkey"
          },
          {
            "name": "outcome",
            "type": "u8"
          },
          {
            "name": "proposedAt",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "pausedSet",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "paused",
            "type": "bool"
          }
        ]
      }
    },
    {
      "name": "poolClaimed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "lp",
            "docs": [
              "The signer who claimed (kept for compatibility)."
            ],
            "type": "pubkey"
          },
          {
            "name": "provider",
            "docs": [
              "The position owner whose shares were claimed (== `lp`)."
            ],
            "type": "pubkey"
          },
          {
            "name": "payout",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "priceFeed",
      "docs": [
        "An on-chain numeric price feed. Designed to be populated by a Switchboard",
        "On-Demand Function (TEE-attested) or a committee multisig bridging a licensed",
        "off-chain index; markets with `RESOLVER_ORACLE_FEED` read it to resolve."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "authority",
            "type": "pubkey"
          },
          {
            "name": "value",
            "type": "i64"
          },
          {
            "name": "decimals",
            "type": "u8"
          },
          {
            "name": "publishedAt",
            "type": "i64"
          },
          {
            "name": "description",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "priceFeedInitialized",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "feed",
            "type": "pubkey"
          },
          {
            "name": "authority",
            "type": "pubkey"
          }
        ]
      }
    },
    {
      "name": "pricePublished",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "feed",
            "type": "pubkey"
          },
          {
            "name": "value",
            "type": "i64"
          },
          {
            "name": "publishedAt",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "redeemed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "payout",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "scalarProposed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "resolver",
            "type": "pubkey"
          },
          {
            "name": "value",
            "type": "i64"
          },
          {
            "name": "proposedAt",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "tradeExecuted",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "isBuy",
            "type": "bool"
          },
          {
            "name": "outcome",
            "type": "u8"
          },
          {
            "name": "collateral",
            "type": "u64"
          },
          {
            "name": "tokens",
            "type": "u64"
          }
        ]
      }
    }
  ]
};
